@extends('layouts.master')

@section('content')
    @include('pages.navbar')

    @include('pages.banner')

    <ul class="list-group">
    <li class="list-group-item">BINARY OPERATIONS</li>
    <li class="list-group-item"> COMPOUND INTEREST</li>
     <li class="list-group-item">CONDITIONAL PROBABILITY</li>
     <li class="list-group-item">CONGRUENT TRIANGLES</li>
     <li class="list-group-item">COSINE FORMULA</li>
  <li class="list-group-item">   EQUATIONS INVOLVING FRACTIONS</li>
   <li class="list-group-item">  FACTORISATIONS</li>
   <li class="list-group-item">  FORCASTING</li>
   <li class="list-group-item">  FRACTIONS </li>
   <li class="list-group-item">  FUNCTIONS</li>
    <li class="list-group-item"> FURTHER MEASURATION</li>
    <li class="list-group-item"> GAME THEORY MOGEL</li>
     <li class="list-group-item"> GENERAL ANGLE</li>
    <li class="list-group-item"> GEOMETRIC AND HARMONIC MEAN</li>
    <li class="list-group-item"> GRADIENTS AND LINES</li>
    <li class="list-group-item"  > GROUPS </li>
    <li class="list-group-item"> HYPOTHESIS TESTING</li>
    <li class="list-group-item"> INDEX NUMBER</li>
    <li class="list-group-item">   INDICES AND LOGARITHM</li>
    <li class="list-group-item">   INVENTORY CONTROL</li>
    <li class="list-group-item">INVESTMENT</li>
    <li class="list-group-item"> LATITUDE AND LONGITUDE</li>
    <li class="list-group-item"> LINEAR EQUATIONS</li>
    <li class="list-group-item"> LINEAR PROGRAMMING PROBLEMS</li>
    <li class="list-group-item"> MARGINAL ANALYSIS</li>
    <li class="list-group-item"> MATRICES,DETERMINANT,COFACTOR,ETC</li>
    <li class="list-group-item"> MEASURES OF PARTITION</li>
    <li class="list-group-item"> MOMENTS,SKEWNESS AND KURTOSIS</li>
    <li class="list-group-item"> NETWORK MODEL</li>
    <li class="list-group-item"> NUMBER BASES</li>
    <li class="list-group-item"> NUMERALS AND NUMBER BASES</li>
    <li class="list-group-item"> PARTIAL FRACTIONS</li>
    <li class="list-group-item"> PERCENTAGE</li>
    <li class="list-group-item"> POISSON DISTRIBUTION</li>
    <li class="list-group-item">POLYNOMIALS</li>
    <li class="list-group-item">PROBABILITY</li>
    <li class="list-group-item"> QUARTILE DEVIATION ,QUARTILE COEFFICIENT</li>
    <li class="list-group-item"> RATIO OF SIMILAR FIGURES</li>
    <li class="list-group-item">  RATIOS OF AN ACUTE ANGLE</li>
    <li class="list-group-item">  REGRESSION AND CORRELATION</li>
    <li class="list-group-item">  RELATIONS,MAPPINGS,FUNCTIONS</li>
    <li class="list-group-item">  SIMPLEX METHOD AND APPLICATION</li>
      <li class="list-group-item"> VALUATION</li>
     <li class="list-group-item"> TIME SERIES</li>
    <li class="list-group-item"> TRGONOMETRY</li>
    <li class="list-group-item"> TRIANGLES AND QUADRILATERAL</li>
    <li class="list-group-item"> TRIGONOMETRICAL RATIO</li>
    <li class="list-group-item">ALGERAIC PROCESS</li>
    <li class="list-group-item">APPROXIMATIONS</li>
    <li class="list-group-item">ARITHMETIC PROGRESSION</li>
    <li class="list-group-item">ASSIGNMENT MODEL</li>
    <li class="list-group-item">BREAKEVEN ANALYSIS</li>
    <li class="list-group-item">ECONOMIC ORDER QUANTITY(EOQ)</li>
    <li class="list-group-item">FACTORS</li>
    <li class="list-group-item">GRAPH</li>
    <li class="list-group-item"> GRAPHICAL INEQUALITIES</li>
    <li class="list-group-item">INEQUALITY</li>
    <li class="list-group-item">INVESTMENT APPRAISALS</li>
    <li class="list-group-item">LEARNING CURVE MODEL</li>
    <li class="list-group-item">LEARNING CURVE MODEL</li>
    <li class="list-group-item">LOGARITHM</li>
    <li class="list-group-item">LOGIC</li>
    <li class="list-group-item">MEAN , MEDIAN ,MODE</li>
    <li class="list-group-item">MEASURES OF LOCATION FROM STATISTICAL DIAGRAM</li>
    <li class="list-group-item"> PROBABILITY(BAYE'S THOREM)</li>
    <li class="list-group-item">PROBLEMS IN THREE DIMENSIONS</li>
    <li class="list-group-item">QUALITY CONTROL MODEL</li>
    <li class="list-group-item"> QUEUE THEOREM</li>
    <li class="list-group-item"> RATES AND TAXES</li>
    <li class="list-group-item"> RATIO</li>
    <li class="list-group-item">  RELATIONS</li>
    <li class="list-group-item">  SAMPLING THEORY AND ESTIMATION</li>
    <li class="list-group-item">  SET THEORY</li>
    <li class="list-group-item">  SIMPLE AND COMPOUND INTEREST</li>
    <li class="list-group-item">  STATISTICS 3( MEAN AND STANDARD DEVIATION)</li>
    <li class="list-group-item">  STATISTICS5(NON-PARAMETRIC METHOD)</li>
    <li class="list-group-item">  STOCKS AND SHARES</li>
    <li class="list-group-item">  SUBSTITUTION AND CHANGE OF SUBJECTS</li>
    <li class="list-group-item">  SURDS</li>
    <li class="list-group-item">  TRANSPORTATION MODEL</li>
    <li class="list-group-item">  TRIANGLES</li>
    <li class="list-group-item">  UTILITY THEOREM</li>
    <li class="list-group-item">  VECTORS WORD PROBLEMS</li>
    <li class="list-group-item">   ALGEBRAIC GRAPH</li>
    <li class="list-group-item">   AREAS AND VOLUMES OF SIMILAR SHAPES</li>
    <li class="list-group-item">   ARITHMETICAL PROCESS</li>
    <li class="list-group-item">   AVERAGES</li>
    <li class="list-group-item">   AXIOMS ,PARALLEL LINES,TRIANGLES AND POLYGON</li>
    <li class="list-group-item">   BASIC COST BEHAVIOUR</li>
    <li class="list-group-item">   REPRESENTATION OF DATA</li>
    <li class="list-group-item">   SIMULTANEOUS EQUATIONS</li>
    <li class="list-group-item">   SINE FORMULA</li>
    <li class="list-group-item">   SOLUTION OF A RIGHT ANGLE TRIANGLE</li>
    <li  class="list-group-item">   STATISTIC 2(GROUPED DATA)</li>
    <li class="list-group-item">  SYMMETRY</li>
    <li class="list-group-item"> APPROXIMATIONS AND ERRORS</li>
    <li class="list-group-item">  ALGEBRA</li>
    <li class="list-group-item">  APPLICATION OF DERIVED FUNCTION OF CALCULUS</li>
    <li class="list-group-item">  AREA OF PLACNE SHAPES</li>
    <li class="list-group-item"> STATISTICS4(PARAMETRIC TEST)</li>
    <li class="list-group-item">ABSORPTION COSTING</li>
    <li class="list-group-item">ACID,BASES AND SALT IN WATER</li>
    <li class="list-group-item">ADVANCED STANDARD COSTING</li>
    <li class="list-group-item">ALTERNATING CURRENT CRICUITS</li>
    <li class="list-group-item">ANALYSIS OF CHANGES IN PROFIT</li>
    <li class="list-group-item">ANGLES</li>
    <li class="list-group-item">AREAS AND VOLUMES OF SOLIDS</li>
    <li class="list-group-item">AREAS OF PLANE FIGURES</li>
    <li class="list-group-item">ATOMIC STRUCTURE AND PERIODIC TABLE</li>
    <li class="list-group-item">ATOMS,MOLECULES AND IONS</li>
    <li class="list-group-item">AUTOCORRELATION</li>
    <li class="list-group-item">AUTOREGRESSIVE AND DISTRIBUTED LAG MODELS</li>
    <li class="list-group-item">BEARING AND DISTANCES</li>
    <li class="list-group-item">BREAK EVEN ANALYSIS</li>
    <li class="list-group-item">BUDGETARY SYSTEM</li>
    <li class="list-group-item">BUDGETING</li>
    <li class="list-group-item">CALCULATIONS USING STANDARD FORM</li>
    <li class="list-group-item">CAPITAL BUDGET DECISION</li>
    <li class="list-group-item">CHEMICAL BOND</li>
    <li class="list-group-item">CHEMICAL EQUILIBRIUM</li>
    <li class="list-group-item">CHEMICAL REACTIONS</li>
    <li class="list-group-item">CIRCLES</li>
    <li class="list-group-item">CLASSICAL NORMAL REGRESSION MODEL</li>
    <li class="list-group-item"> COMPLEX NUMBERS</li>
    <li class="list-group-item">COMPOSITION OFMATTER</li>
    <li class="list-group-item">CONGRUENT TRIANGLES</li>
    <li class="list-group-item">CONSTRUCTION AND LOCI</li>
    <li class="list-group-item">CONTRACT COSTING</li>
    <li class="list-group-item">COORDINATE GEOMETRY</li>
    <li class="list-group-item">COORDINATES IN SPACE</li>
    <li class="list-group-item"> COST ANALYSIS </li>
    <li class="list-group-item"> COST BEHAVIOUR</li>
    <li class="list-group-item"> COSTING JOINT PRODUCTS</li>
    <li class="list-group-item"> COST-VOLUME-PROFIT-ANALYSIS</li>
    <li class="list-group-item"> D-BLOCK ELEMENTS</li>
    <li class="list-group-item"> DECISION MAKING</li>
    <li class="list-group-item"> DECISION THEOREM(EXPECTATION VALUE)</li>
    <li class="list-group-item"> DECISION THEOREM(SENSITIVITY ANALYSIS)</li>
    <li class="list-group-item">  DEDUCTIVE REASONING</li>
    <li class="list-group-item"> DIVISIONAL PERFORMANCE EVALUATION</li>
    <li class="list-group-item"> DUMMY VARIABLE REGRESSION MODEL</li>
    <li class="list-group-item"> DYNAMIC ECONOMETRICS</li>
    <li class="list-group-item"> ECONOMIC MODELING</li>
    <li class="list-group-item"> ELASTICITY AND SIMPLE HARMONIC MOTION</li>
    <li class="list-group-item"> ELECTRIC CIRCUITS</li>
    <li class="list-group-item"> ELECTRIC FIELD</li>
    <li class="list-group-item"> ELECTRIC FORCES AND ELECTRIC FIELD</li>
    <li class="list-group-item"> ELECTRIC POTENTIAL ENERGY AND ELECTRIC POTENTIAL</li>
    <li class="list-group-item"> ELECTROCHEMISTRY</li>
    <li class="list-group-item"> ELECTROMAGNETIC INDUCTION</li>
    <li class="list-group-item"> ELECTROMAGNETIC WAVES</li>
    <li class="list-group-item"> ELEMENTARY PARTICLES</li>
    <li class="list-group-item"> ENERGY,HEAT AND THERMOCHEMISTRY</li>
    <li class="list-group-item"> ENTROPY, FREE ENERGY AND EQUILIBRIUM</li>
    <li class="list-group-item">FLUIDS</li>
    <li class="list-group-item">FORCES NEWTON'S LAWS OF MOTION</li>
    <li class="list-group-item">FORECASTING</li>
    <li class="list-group-item">FORMULAE EXPRESSION</li>
    <li class="list-group-item">FRACTIONS IN ALGEBRA</li>
    <li class="list-group-item">FUNCTIONAL GROUPS AND BIOMOLECULES</li>
    <li class="list-group-item"> GAME THEORY</li>
    <li class="list-group-item"> GEOMETRIC PROGRESSION</li>
    <li class="list-group-item"> GEOMETRICAL APPLICATION OF MATRICES</li>
    <li class="list-group-item">GEOMETRICAL RATIOS</li>
    <li class="list-group-item"> HEAT</li>
    <li class="list-group-item">  HYDROCARBONS</li>
    <li class="list-group-item">  HYDROGEN AND THE S-BLOCK ELEMENTS</li>
    <li class="list-group-item">  IDEAL GAS LAW AND KINETIC THEORY</li>
    <li class="list-group-item">   IMPULSE AND MOMENTUM</li>
    <li class="list-group-item">  INEQUALITIES IN GEOMETRY</li>
    <li class="list-group-item">  INTERFERENCE AND THE WAVE NATURE OF LIGHT</li>
    <li class="list-group-item">  INVENTORY CONTROL MODEL</li>
    <li class="list-group-item">  INVERSE AND CONTRAPOSITIVES</li>
    <li class="list-group-item">  INVESTMENT APPRASAL</li>
    <li class="list-group-item">  IONIZATION RADIATION,NUCLEAR ENERGY AND ELEMENTARY PARTICLES</li>
    <li class="list-group-item"> JOB COSTING</li>
    <li class="list-group-item"> JUST-IN-TIME-INVENTORY</li>
    <li class="list-group-item"> KINEMATICS IN ONE DIMENSION</li>
    <li class="list-group-item"> KINEMATICS IN TWO DIMENSION</li>
    <li class="list-group-item"> LABOUR COSTING</li>
    <li class="list-group-item"> LEARNING CURVE THEORY</li>
    <li class="list-group-item"> LINEAR PROGRAMMING MODEL</li>
    <li class="list-group-item"> LINEAR PROGRAMMING TECHNIQUES</li>
    <li class="list-group-item"> LINES</li>
    <li class="list-group-item"> LIQUIDS AND SOLIDS</li>
    <li class="list-group-item"> LOCI</li>
    <li class="list-group-item"> MAGNETIC FORCES AND MAGNETIC FIELDS</li>
    <li class="list-group-item"> MARGINAL COSTING</li>
    <li class="list-group-item"> MARGINAL COSTING AND DECISION MAKING</li>
    <li class="list-group-item"> MARKOV ANALYSIS</li>
    <li class="list-group-item"> MATERIAL PRICING</li>
    <li class="list-group-item"> MATERIALS PRICING</li>
    <li class="list-group-item"> MATTER AND REACTIONS</li>
    <li class="list-group-item"> MEASURATION</li>
    <li class="list-group-item"> MEASURES OF CENTRAL TENDENCEIES</li>
    <li class="list-group-item"> MULTICOLLINEARITY</li>
    <li class="list-group-item"> NATURE OF ATOM</li>
    <li class="list-group-item">   NETWORK MODELS</li>
    <li class="list-group-item">  NON-LINEAR REGRESSION MODEL</li>
    <li class="list-group-item">  NUCLEAR CHEMISTRY</li>
    <li class="list-group-item"> NUCLEAR ENERGY</li>
    <li class="list-group-item">NUCLEAR PHYSICS AND RADIO ACTIVITY</li>
    <li class="list-group-item"> OPERATING STATEMENTS</li>
    <li class="list-group-item"> OVERHEADS</li>
    <li class="list-group-item"> PANEL DATA REGRESSION MODEL</li>
    <li class="list-group-item"> PARALLEL LINES AND PLANES</li>
    <li class="list-group-item"> PARTICLES AND WAVES</li>
    <li class="list-group-item"> P-BLOCK ELEMENTS</li>
    <li class="list-group-item"> PERCENTILE</li>
    <li class="list-group-item">PLANES </li>
    <li class="list-group-item">  PLANES AND LINES IN SPACE</li>
    <li class="list-group-item">  POINTS </li>
    <li class="list-group-item"> POINTS,LINES,PLANES AND ANGLES</li>
    <li class="list-group-item"> PRINCIPLE OF LINEAR SUPERPOSITION AND INTERFERENCE PHENOMENA</li>
    <li class="list-group-item"> PROCESS COSTING</li>
    <li class="list-group-item">PROJECT MANAGEMENT</li>
    <li class="list-group-item">PROPERTIES AND SOLUTIONS</li>
    <li class="list-group-item">PROPERTIES OF GASES</li>
    <li class="list-group-item"> PROPETIES , MEASUREMENTS AND UNITS</li>
    <li class="list-group-item"> QUADRATIC EQUATIONS</li>
    <li class="list-group-item">   QUADRILATERALS</li>
    <li class="list-group-item">  QUALITATIVE RESPONSE REGRESSION MODEL</li>
    <li class="list-group-item">  QUARTILE, SEMI-INTERQUARTILE</li>
    <li class="list-group-item"> RATES AND EQUILIBRIUM</li>
    <li class="list-group-item"> RATIONAL AND NON-RATIONAL NUMBERS</li>
    <li class="list-group-item"> REACTION STOICHIOMETRY</li>
    <li class="list-group-item"> REFLECTION OF LIGHT: MIRRORS</li>
    <li class="list-group-item"> REFRACTION OF LIGHT: LENSES AND OPTICAL INSTRUMENTS</li>
    <li class="list-group-item"> REGRESSION ANALYSIS</li>
    <li class="list-group-item"> RELEVANT COSTIN NPN-ROUTINE DECISIONS</li>
    <li class="list-group-item"> RIGHT ANGLES</li>
    <li class="list-group-item"> ROTATIONAL DYNAMICS</li>
    <li class="list-group-item"> ROTATIONAL KINEMATICS</li>
    <li class="list-group-item">SHAPES OF MOLECULES</li>
    <li class="list-group-item">SIMILAR POLYGONS</li>
    <li class="list-group-item">SIMPLE HARMONIC MOTION</li>
  <li class="list-group-item">  SIMPLEX </li>
   <li class="list-group-item"> SPECIAL RELATIVITY</li>
   <li> SPHERICAL TRIGONOMETRY</li>
    <li>STANDARD COSTING</li>
 <li class="list-group-item">   STATISTIC 1(UNGROUP DATA)</li>
  <li class="list-group-item">  STATISTICAL QUALITY CONTROL</li>
 <li class="list-group-item">   SURFACES</li>
  <li class="list-group-item">  TEMPERATURE AND HEAT</li>
  <li class="list-group-item">  THERMODYNAMICS</li>
  <li class="list-group-item">  TIME SERIES ECONOMETRICS</li>
    <li class="list-group-item">TRANSFER OF HEAT</li>
   <li class="list-group-item" > TRANSFER PRICING DECISION</li>
    <li class="list-group-item">TRANSFORMATIONS</li>
  <li class="list-group-item">  TWO VARIABLE LINEAR PROGRESSION MODEL</li>
   <li class="list-group-item"> TWO VARIABLE REGRESSION ANALYSIS</li>
   <li class="list-group-item"> TWO VARIABLE REGRESSION MODEL </li>
  <li class="list-group-item">  VARIANCE ANALYSIS</li>
    <li class="list-group-item">VARIATION </li>
   <li class="list-group-item"> VECTOR GEOMETRIC</li>
   <li class="list-group-item"> WAITING LINES MODEL</li>
  <li class="list-group-item">  WAVE NATURE OF LIGHT</li>
    <li class="list-group-item">WAVES AND SOUND</li>
    <li class="list-group-item">WORK AND ENERGY<li>
    </ul>
    @include('pages.footer')
@endsection